# Config for https://github.com/toolmantim/release-drafter
name-template: 'Twirl, the Play template engine $NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'

change-template: '- $TITLE #$NUMBER by [@$AUTHOR](https://github.com/$AUTHOR)'
template: |
  ## Changes

  $CHANGES
