name: Publish

on:
  push:
    branches: # Snapshots
      - main
    tags: ["*"] # Releases

jobs:
  publish-artifacts:
    name: Publish / Artifacts
    uses: ihostage/.github/.github/workflows/publish.yml@main
