name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate:
    name: "Code validations (headerCheck, scalafmt, mima)"
    uses: ihostage/.github/.github/workflows/sbt.yml@main
    with:
      command: ./scripts/validate-code.sh

  tests:
    needs:
      - validate

    name: "Run tests with Scala ${{ matrix.scala }} and AdoptOpenJDK ${{ matrix.java }}"
    uses: ihostage/.github/.github/workflows/sbt-matrix.yml@main
    with:
      command: ./scripts/test-code.sh
      java: >-
        ["8", "11"]
      scala: >-
        ["2.12.15", "2.13.7"]

  docs:
    needs:
      - tests

    name: "Validate documentation"
    uses: ihostage/.github/.github/workflows/sbt.yml@main
    with:
      command: ./scripts/validate-docs.sh
